# Generated by Django 3.1.5 on 2021-01-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed'), ('in progress', 'in progress')], max_length=100),
        ),
    ]
